# Generated by Django 5.0.4 on 2024-04-29 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriminalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime', models.CharField(max_length=30)),
                ('trest_type', models.CharField(max_length=30)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('end_date', models.DateField(verbose_name='end_date')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('sex', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('case_type', models.CharField(max_length=30)),
                ('detective', models.CharField(max_length=30)),
                ('judge', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('criminal_history_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.criminalhistory')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.case')),
            ],
        ),
        migrations.CreateModel(
            name='Defendats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.case')),
                ('peson_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.person')),
            ],
        ),
        migrations.AddField(
            model_name='criminalhistory',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.person'),
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=500)),
                ('protection', models.BooleanField()),
                ('case_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.case')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.person')),
            ],
        ),
    ]
