# Generated by Django 5.0.4 on 2024-04-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SKJproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defendats',
            new_name='Defendat',
        ),
        migrations.RenameModel(
            old_name='Witness',
            new_name='Witnes',
        ),
    ]
