# Generated by Django 5.0.4 on 2024-05-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKJproject', '0002_rename_defendats_defendat_rename_witness_witnes'),
    ]

    operations = [
        migrations.AddField(
            model_name='criminalhistory',
            name='case_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.case'),
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKJproject.case')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SKJproject.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Defendat',
        ),
    ]
