# Generated by Django 5.0.4 on 2024-05-03 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKJproject', '0003_criminalhistory_case_id_defendant_delete_defendat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.case'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SKJproject.person'),
        ),
    ]
