# Generated by Django 5.0.4 on 2024-05-03 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SKJproject', '0004_alter_defendant_case_alter_defendant_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SKJproject.case'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SKJproject.person'),
        ),
    ]
